// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByxSEwA49rPqo532-ppLRNCgBLLNsom1A',
    appId: '1:862588647458:web:010f20d6ddf613944d727b',
    messagingSenderId: '862588647458',
    projectId: 'hackathon2025app',
    authDomain: 'hackathon2025app.firebaseapp.com',
    storageBucket: 'hackathon2025app.firebasestorage.app',
    measurementId: 'G-MCGEZ6PE8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwzTrRFGrmyizI7KH_H6B2PjoUTHXPq0',
    appId: '1:862588647458:android:8012023c6edd9b8f4d727b',
    messagingSenderId: '862588647458',
    projectId: 'hackathon2025app',
    storageBucket: 'hackathon2025app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNpDwfY-cKECXL2cXwDeSUIUoGFINTS4U',
    appId: '1:862588647458:ios:4ea346d6b23bc4014d727b',
    messagingSenderId: '862588647458',
    projectId: 'hackathon2025app',
    storageBucket: 'hackathon2025app.firebasestorage.app',
    iosBundleId: 'com.hackathonapp.hackathon2025app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNpDwfY-cKECXL2cXwDeSUIUoGFINTS4U',
    appId: '1:862588647458:ios:4ea346d6b23bc4014d727b',
    messagingSenderId: '862588647458',
    projectId: 'hackathon2025app',
    storageBucket: 'hackathon2025app.firebasestorage.app',
    iosBundleId: 'com.hackathonapp.hackathon2025app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByxSEwA49rPqo532-ppLRNCgBLLNsom1A',
    appId: '1:862588647458:web:e16c8c29d1bfcec34d727b',
    messagingSenderId: '862588647458',
    projectId: 'hackathon2025app',
    authDomain: 'hackathon2025app.firebaseapp.com',
    storageBucket: 'hackathon2025app.firebasestorage.app',
    measurementId: 'G-H2T66DKH17',
  );

}